### ISSUE TITLE
Videos no longer working in Firefox after upgrade to channel version 12

### ISSUE THREAD

**Issue by intelliant01** [learningequality/sushi-chef-khan-academy#3]
Am experiencing an error message while attempting to play only Khan Academy videos after upgrading to channel version 12.
Error experienced only in Firefox (tested with multiple versions on multiple OS platforms). Works fine in Chrome.
Kolibri 0.10.0 and 0.10.1.
Last channel version we had was 7.

![463567057b74993490571f4435320a718091d089_1_690x443](https://user-images.githubusercontent.com/2577060/44854337-e789dd80-ac85-11e8-9285-7b57a960d6c2.PNG)

Reference: http://community.learningequality.org/t/kolibiri-not-able-to-view-video-in-firefox-only/725

**Comment by radinamatic** [comment]
Managed to replicate on both Windows and Ubuntu, occuring only on KA EN channel (KA ES, CK12 and others with videos seem unaffected):

![2018-09-05_22-32-50](https://user-images.githubusercontent.com/1457929/45127129-2c76ae00-b177-11e8-9c98-5411e983ddb7.png)

![2018-09-05_22-51-27](https://user-images.githubusercontent.com/1457929/45127170-55973e80-b177-11e8-9c60-c185e02fb5d3.png)

On Ubuntu it happens with the `restricted-extras` package installed, which would exclude any missing codec issue (as described in our documentation).

Could it be because the videos are interpreted as `video/3gpp` content type...?

### Errors and logs
```
HTTP "Content-Type" of "video/3gpp" is not supported. Load of media resource https://kolibridemo.learningequality.org/content/storage/f/9/f9b22cdb885b42f38fa29282181dc5f4.mp4 failed
```

### Context

 * 0.10.2 (demo server)
 * Windows 10 & Ubuntu 16.04
 * Firefox 62.0

**Comment by radinamatic** [comment]
cc @jayoshih @kollivier

**Comment by intelliant01** [comment]
Is fixed in version 13 of the channel.
Do note that the issue was specific to Maths videos only as I re-checked before upgrade.
