### ISSUE TITLE
KA Gujarati YouTube channel available as a Kolibri channel?

### ISSUE THREAD

**Issue by intelliant01** [learningequality/sushi-chef-khan-academy#6]
Is there any work underway to make Khan Academy Gujarati YouTube channel/playlist (https://www.youtube.com/channel/UCaglh99xdT0llj9Fn2RIsGQ) available as a Kolibri channel  ?

@ralphiee22 is this commit (https://github.com/learningequality/sushi-chef-khan-academy/commit/3448993900b7478a3a6b65be39f46d217e7ed959) related to any work in this direction?

**Comment by ralphiee22** [comment]
Hey @intelliant01, this should be pretty easy to do. Could you give me your studio email so I can share the channel with you once it has been completed. 
And I'm assuming you want the playlist style because it has more science related content as opposed to https://gu.khanacademy.org/? Which seems to only have a very small subset of math.

**Comment by intelliant01** [comment]
Hi @ralphiee22 , my studio email id is shrenik@recherchetech.com . 

There is no particular reason to prefer the YT channel/playlist over the gu.khanacademy.org. I was also not aware of the later. Thanks for letting me know. My aim is just to get whatever KA Gujarati content that is available to the teachers and then work with them to organise it as may be helpful for them and the students.

**Comment by intelliant01** [comment]
@ralphiee22  thanks, now I see the channel with 77 videos. The YT channel has 1800+ videos. Are you working on importing those as well?
Also what's the plan with the gu.khanacademy.org content?

**Comment by intelliant01** [comment]
@ralphiee22 I see the complete upload. Thanks a ton.

**Comment by intelliant01** [comment]
@ralphie22 Is the public release of the channel pending due to lack of grouping into topic nodes?

Can I be of any help to enable the public release?

**Comment by intelliant01** [comment]
@ralphiee22 May I get write access to the channel so that I may start organising the content into a topic tree as per the prescribed curriculum in the state of Gujarat, India?
Or should I create a new channel and copy over the contents for reorganising into topics?
And would also request you to do the needful to update the channel with contents of the YouTube channel as there are many new videos.

**Comment by ralphiee22** [comment]
Whenever we re-run the chef, it will overwrite any structural changes to the original channel. I think the best option is to create a new channel and copy over the contents for organizing. And yes, I can update the channel to get the latest videos.

**Comment by ivanistheone** [comment]
Hi @intelliant01 . I wanted to add a few details for next steps:
1. Create a new empty channel called `Khan Academy (ગુજરાતી) DERIVATIVE`. We'll call this the "Derivative channel" and this is the official channel that users will see in the end.
2. Wait until Ralphie updates the [`Khan Academy (ગુજરાતી)` SOURCE channel](https://studio.learningequality.org/channels/5357e52581c3567da4f56d56badfeac7/view/5357e52)
3. Use the import from channel and clipboard to import and content from the SOURCE channel to the DERIVATIVE channel and organize into topics.
4. When you're done importing and curating, we'll make the DERIVATIVE channel the official one (the source channel will remain hidden since it is not well-organized).

Please let us know the channel id for the DERIVATIVE channel once you create it so we can keep track of it.  In the future when we run the chef, the SOURCE channel will get overwritten but the manual curation and alignment steps you did in the derivative channel will not be changed. We can then use the Studio SYNC nodes feature to update the DERIVATIVE channel to the latest content.

**Comment by intelliant01** [comment]
Hi @ralphiee22 @ivanistheone, Had already started working towards the workflow you have suggested day before. Herein is the channel id - ```difit-norak``` .
Have given it the name ```Khan Academy (ગુજરાતી) - GSEB``` inline with regional education board's curriculum which will serve as the guideline for the classification.
Let's rock.

**Comment by intelliant01** [comment]
@ivanistheone pls share some more details about how the Studio SYNC nodes feature works.

**Comment by intelliant01** [comment]
@ralphiee22 Please re-run the chef whenever you can as we have the "derivative" channel in works and content organisers will be working soon.

**Comment by ivanistheone** [comment]
> @ivanistheone pls share some more details about how the Studio SYNC nodes feature works.

When you import content node `C` form channel `X` into channel `Y`, you get a clone of the content node `CC` and Studio keeps track of the original node that was cloned.

Suppose now the channel `X` gets updated and the node `C` gets updated: it could have more subtitles files added to it, change title, or description, or other modification. This update will not be automatically reflected in the derivative channel `Y` since the update was on channel `X`.

Using the SYNC option on channel `Y`, will look for updates on all the original source nodes and update the derivative channel to the latest content. So in this case, during SYNC on channel `Y`, the copy node `CC` will get updated to the latest updates from node `C` in channel `X`.

Note the channel SYNC feature will not work if new nodes are added to the source channel (SYNC only works for content-nodes, so will not track new added nodes) so it would be best to wait until the latest version of the channel is available before starting the curation.

**Comment by ralphiee22** [comment]
@intelliant01, the gujarati channel should have been updated. Please let me know if it contains the latest videos.

**Comment by intelliant01** [comment]
@ralphiee22 Doesn't look like that the changes have been published. Still the count is ```1825 Resources``` whereas the YT channel contains 1900+ (a dozen may have been added in the last day)
The ```Last Published``` date is of Oct, 2018.
Spotted a slight UI error - ```Created``` date is Jan, 2019. Should have been ```Updated``` instead.

![screenshot_20190130-193259__01](https://user-images.githubusercontent.com/2577060/51986605-7ea6cb80-2498-11e9-99c4-345372eb784b.jpg)

**Comment by intelliant01** [comment]
@ivanistheone thanks for the detailed explanation of the SYNC feature. This isn't in the studio documentation and should be added therein.

However, I don't see much of a utility of this feature in this scenario as most of the content enrichment on all content nodes will happen in the derivative channel Y only. Given the nature of YouTube channels, a video once published can't change, and I guess its meta data is not being pulled in by the script run by @ralphiee22 , hence no aspect of C shall change on channel X.

One concern - I hope that even hitting a SYNC on Y when nothing has been added to C on X will not blank out the enhancements of CC. Please confirm.


.

**Comment by ralphiee22** [comment]
@intelliant01 I will look into why the latest videos have not been added.

Also below you can find a screenshot of what the SYNCing interface looks like. If you edit things like the `title, description` in CC and check the `details` box and hit SYNC. CC will be overwritten with the information from C. I imagine in your case it would be ok to check `Files` in case subtitles get updated.
![screen shot 2019-01-30 at 10 08 40 am](https://user-images.githubusercontent.com/6361732/52002501-109ddc80-2477-11e9-9d1b-7ac49b71afec.png)

**Comment by ralphiee22** [comment]
@intelliant01 Latest videos should now be present.

**Comment by intelliant01** [comment]
> This isn't in the studio documentation and should be added therein.

I see it there https://kolibri-studio.readthedocs.io/en/develop/add_content.html#sync

But SYNC doesn't work as expected, at least for what I have tried. Possibly related issue https://github.com/learningequality/studio/issues/1084

@ralphiee22 How can I get the latest videos published on YouTube into the Kolibri channel on my own or will you be doing it periodically by running the script?

**Comment by ralphiee22** [comment]
@intelliant01 I am a little confused by what you were trying to do in https://github.com/learningequality/studio/issues/1084#issuecomment-461719043. Maybe you were just trying to test the feature? But you should never edit nodes on the source channel because they will always get overwritten by an update. The syncing not working as expected sounds like a different issue though.
And yes I will be running a script to update the Gujarati channel. Will there be continuous work on publishing youtube videos?

**Comment by intelliant01** [comment]
@ralphiee22 Yes I was testing the SYNC feature as there is no other way I could simulate changes in the source channel via an import. I hope that addresses the confusion.

> And yes I will be running a script to update the Gujarati channel. Will there be continuous work on publishing youtube videos?

Yes, for now it seems it shall be continuos work at least for this channel as they keep on adding new videos on a weekly basis. There are a few other YT channels also that have been curated by teachers who would want their work to be ported to Kolibri and I am in talks with them as well.

**Comment by intelliant01** [comment]
@ralphiee22 In response to your early statements -
> And I'm assuming you want the playlist style because it has more science related content as opposed to https://gu.khanacademy.org/? Which seems to only have a very small subset of math.

Seems now that gu.khanacademy.org is more aligned to what is needed by the schools here in Gujarat, India, as compared to the content in the YouTube channel that my team and some school teachers have been slogging hard to arrange :) . 

Also the maintainers of gu.ka are now fast populating and organising the content (videos and exercises) on this site for both Math and Science. KA local reps have also started training teachers with the permission of the local education body herein for using the online content from this website. 

Can you help with this import or should we be adopting some other approach? 

An early response on this will be highly appreciated so that the adoption of the online content after the training will definitely hit a roadblock as none of the schools can rely on the internet connections they have. Hence having it all offline on Kolibri will be a big plus for all.

**Comment by ralphiee22** [comment]
@intelliant01 I'll look into this. I'll get back to you with progress on the channel.

**Comment by ralphiee22** [comment]
@intelliant01 I have sent you an invite to a TEST CHANNEL of the khan academy gujarati content. If you can review and let me know if it meets your needs, then I can push it to the real Gujarati channel. Please do not use this channel for anything other than Quality Assurance.

**Comment by intelliant01** [comment]
@ralphiee22 Thanks. I have copied over the contents from the TEST CHANNEL to channel with token ```difit-norak```. Next, I shall get the teachers to check the same and let you know. 

I guess by _real Gujarati channel_, you mean the one with token ```modok-nilan```.  Based on the pace of mapping at gu.ka...org and the satisfaction of the teachers, I shall let you know if we need to persist with this channel any more. If all are satisfied with ```difit-norak```, then we will not need ```modok-nilan``` at all.

For now,  if possible, rename the two imported channels to indicate their source by attaching a suffix - ```YouTube``` and ```Portal``` or ```gu.ka.org```
